import { useState } from 'react';
import { C } from '../theme.js';
import { formatRub } from '../utils.js';
import { Th, Td } from '../components/ui.jsx';

// ====== ЭКРАН 5: ЗАКУПКИ ======
export function PurchasesScreen({ purchaseRequests, supermarkets, onFulfill }) {
  const [filter, setFilter] = useState('pending');
  const filtered = filter === 'all' ? purchaseRequests : purchaseRequests.filter((pr) => pr.status === filter);

  const getMaterial = (id) => supermarkets.raw.find((r) => r.id === id);

  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <h1 style={{ fontSize: 26, fontWeight: 700, color: C.navy, margin: '0 0 6px' }}>Закупки</h1>
        <p style={{ color: C.textMuted, fontSize: 14, margin: 0 }}>Автоматически сгенерированные заявки на пополнение сырья · pull-сигнал от супермаркета</p>
      </div>

      <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
        {[
          { id: 'pending', label: `Активные (${purchaseRequests.filter((p) => p.status === 'pending').length})` },
          { id: 'delivered', label: `Поставлены (${purchaseRequests.filter((p) => p.status === 'delivered').length})` },
          { id: 'all', label: `Все (${purchaseRequests.length})` },
        ].map((f) => (
          <button key={f.id} onClick={() => setFilter(f.id)} style={{
            padding: '8px 14px', border: `1px solid ${filter === f.id ? C.navy : C.border}`,
            background: filter === f.id ? C.navy : '#fff',
            color: filter === f.id ? '#fff' : C.text,
            borderRadius: 8, fontSize: 13, cursor: 'pointer', fontWeight: 500,
          }}>{f.label}</button>
        ))}
      </div>

      {filtered.length === 0 ? (
        <div style={{ background: '#fff', border: `1px dashed ${C.border}`, borderRadius: 12, padding: 40, textAlign: 'center' }}>
          <div style={{ fontSize: 14, color: C.textMuted }}>В этой категории нет заявок</div>
        </div>
      ) : (
        <div style={{ background: '#fff', border: `1px solid ${C.border}`, borderRadius: 12, overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
            <thead>
              <tr style={{ background: C.bg, borderBottom: `1px solid ${C.border}` }}>
                <Th>Номер</Th>
                <Th>Материал</Th>
                <Th>Количество</Th>
                <Th>Сумма (расчётно)</Th>
                <Th>Создана</Th>
                <Th>Тип</Th>
                <Th>Статус</Th>
                <Th>Действие</Th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((pr) => {
                const m = getMaterial(pr.materialId);
                if (!m) return null;
                return (
                  <tr key={pr.id} style={{ borderBottom: `1px solid ${C.border}` }}>
                    <Td><span style={{ fontFamily: 'monospace', fontWeight: 600, color: C.navy }}>{pr.id}</span></Td>
                    <Td>{m.name}</Td>
                    <Td><span style={{ fontWeight: 600 }}>{pr.qty}</span> {m.unit}</Td>
                    <Td>{formatRub(pr.qty * m.price)}</Td>
                    <Td><span style={{ fontSize: 12 }}>{pr.createdAt}</span></Td>
                    <Td>
                      {pr.autoGenerated ? (
                        <span style={{ background: C.purpleLight, color: C.purple, padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 500 }}>Автоматическая</span>
                      ) : (
                        <span style={{ background: C.ice, color: C.navy, padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 500 }}>Ручная</span>
                      )}
                    </Td>
                    <Td>
                      {pr.status === 'pending' ? (
                        <span style={{ background: C.yellowLight, color: C.yellow, padding: '3px 10px', borderRadius: 12, fontSize: 12, fontWeight: 500 }}>Ожидает</span>
                      ) : (
                        <span style={{ background: C.greenLight, color: C.green, padding: '3px 10px', borderRadius: 12, fontSize: 12, fontWeight: 500 }}>Поставлена</span>
                      )}
                    </Td>
                    <Td>
                      {pr.status === 'pending' && (
                        <button onClick={() => onFulfill(pr.id)} style={{
                          padding: '5px 10px', background: C.green, color: '#fff', border: 'none',
                          borderRadius: 6, fontSize: 12, fontWeight: 600, cursor: 'pointer',
                        }}>Принять поставку</button>
                      )}
                    </Td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <div style={{ marginTop: 16, padding: 12, background: C.ice, border: `1px solid ${C.navyLight}`, borderRadius: 8, fontSize: 12, color: C.navy }}>
        <strong>Принцип работы:</strong> когда уровень любого материала в супермаркете падает до минимума или ниже, система автоматически создаёт заявку на пополнение до максимального уровня. После приёма поставки уровень в супермаркете восстанавливается. Это ключевой механизм pull-сигнала в вытягивающей системе.
      </div>
    </div>
  );
}
