import { useState } from 'react';
import { NavLink, Routes, Route, Navigate } from 'react-router-dom';
import { C } from './theme.js';
import {
  STAGES,
  STAGE_CONSUMPTION,
  initialOrders,
  initialSupermarkets,
  initialPurchaseRequests,
  initialShippedHistory,
  nextOrderId,
  nextPurchaseRequestId,
} from './data.js';
import { SonyaLogo } from './components/SonyaLogo.jsx';
import { OrderModal } from './components/OrderModal.jsx';
import { NewOrderModal } from './components/NewOrderModal.jsx';
import { Dashboard } from './pages/Dashboard.jsx';
import { OrdersScreen } from './pages/OrdersScreen.jsx';
import { KanbanBoard } from './pages/KanbanBoard.jsx';
import { SupermarketScreen } from './pages/SupermarketScreen.jsx';
import { PurchasesScreen } from './pages/PurchasesScreen.jsx';
import { AnalyticsScreen } from './pages/AnalyticsScreen.jsx';

// ====== ОСНОВНОЙ КОМПОНЕНТ ======
// Здесь находится всё состояние приложения. Все экраны получают данные через props
// и при действиях вызывают функции, которые меняют это состояние — отсюда «связанная логика».
export default function App() {
  const [orders, setOrders] = useState(initialOrders);
  const [supermarkets, setSupermarkets] = useState(initialSupermarkets);
  const [purchaseRequests, setPurchaseRequests] = useState(initialPurchaseRequests);
  const [shippedHistory] = useState(initialShippedHistory);
  const [selectedOrder, setSelectedOrder] = useState(null);
  const [isNewOrderOpen, setIsNewOrderOpen] = useState(false);
  const [notifications, setNotifications] = useState([]);

  // Добавить уведомление (исчезает через 4 сек)
  const pushNotification = (text, type = 'info') => {
    const id = Date.now() + Math.random();
    setNotifications((prev) => [...prev, { id, text, type }]);
    setTimeout(() => {
      setNotifications((prev) => prev.filter((n) => n.id !== id));
    }, 4000);
  };

  // Создать новый заказ — добавляется в planned, в производство не запускается до перемещения на канбане
  const createOrder = ({ clientId, modelId, qty, deadline }) => {
    const newOrder = {
      id: nextOrderId(),
      clientId, modelId, qty, deadline,
      status: 'planned',
      stageIdx: -1,
      startedAt: null,
      timeOnStage: 0,
      consumed: {},
    };
    setOrders((prev) => [newOrder, ...prev]);
    pushNotification(`Создан заказ ${newOrder.id}`, 'success');
    setIsNewOrderOpen(false);
  };

  // Списать материалы со склада сырья (для конкретной модели и количества)
  // Чистая функция: считает новое состояние и побочные эффекты заранее, потом применяет.
  const consumeMaterials = (stageIdx, modelId, qty) => {
    const recipe = STAGE_CONSUMPTION[stageIdx]?.[modelId];
    if (!recipe) return;

    // Считаем новое состояние супермаркета
    const newRaw = supermarkets.raw.map((item) => {
      const consumption = recipe[item.id];
      if (!consumption) return item;
      const consumedAmount = Math.ceil(consumption * Math.min(qty, 20)); // потолок для больших партий
      return { ...item, current: Math.max(0, item.current - consumedAmount) };
    });

    // Какие материалы пересекли минимум вниз — на них нужна автозаявка
    const newAutoRequests = [];
    newRaw.forEach((item, i) => {
      const oldCurrent = supermarkets.raw[i].current;
      if (oldCurrent > item.min && item.current <= item.min) {
        // Проверяем дубликат позже — после получения актуального списка заявок
        const needed = item.max - item.current;
        newAutoRequests.push({
          id: nextPurchaseRequestId(),
          materialId: item.id,
          materialName: item.name,
          qty: needed,
          status: 'pending',
          createdAt: new Date().toLocaleString('ru-RU').slice(0, 16),
          autoGenerated: true,
        });
      }
    });

    // Применяем новые состояния
    setSupermarkets((prev) => ({ ...prev, raw: newRaw }));
    if (newAutoRequests.length > 0) {
      setPurchaseRequests((prev) => {
        const result = [...prev];
        newAutoRequests.forEach((req) => {
          if (!result.some((pr) => pr.materialId === req.materialId && pr.status === 'pending')) {
            result.unshift(req);
            pushNotification(`Автозаявка ${req.id}: ${req.materialName}`, 'warning');
          }
        });
        return result;
      });
    }
  };

  // Прибавить готовую продукцию на склад ГП (когда заказ дошёл до конца производства)
  const addToFinishedStock = (modelId) => {
    setSupermarkets((prev) => ({
      ...prev,
      finished: prev.finished.map((f) => {
        if (f.modelId !== modelId) return f;
        // Прибавляем символически 1 шт. на склад вне зависимости от размера заказа
        // (заказ напрямую отгружается клиенту, на склад ГП кладётся «буферный» комплект)
        return { ...f, current: Math.min(f.max, f.current + 1) };
      }),
    }));
  };

  // Перенос заказа на канбан-доске (имитация канбан-сигнала)
  // Здесь же происходит списание материалов по этапам и пополнение склада ГП.
  const moveOrder = (orderId, direction) => {
    setOrders((prev) => prev.map((o) => {
      if (o.id !== orderId) return o;
      const newIdx = o.stageIdx + direction;
      const newConsumed = { ...(o.consumed || {}) };

      // Если двинулись назад в planned
      if (newIdx < 0) {
        pushNotification(`${orderId} возвращён в план`, 'info');
        return { ...o, status: 'planned', stageIdx: -1, timeOnStage: 0 };
      }

      // Если двинулись вперёд через все переделы → готов к отгрузке
      if (newIdx >= STAGES.length) {
        addToFinishedStock(o.modelId, o.qty);
        pushNotification(`${orderId} готов к отгрузке`, 'success');
        return { ...o, status: 'ready_to_ship', stageIdx: STAGES.length, timeOnStage: 0 };
      }

      // Двигаемся вперёд: проверяем, списали ли материалы для этого этапа
      if (direction > 0 && STAGE_CONSUMPTION[newIdx] && !newConsumed[`s${newIdx}`]) {
        consumeMaterials(newIdx, o.modelId, o.qty);
        newConsumed[`s${newIdx}`] = true;
      }

      return {
        ...o,
        status: 'in_production',
        stageIdx: newIdx,
        timeOnStage: 0,
        consumed: newConsumed,
        startedAt: o.startedAt || new Date().toLocaleString('ru-RU').slice(0, 16),
      };
    }));
  };

  // Отгрузка заказа из ready_to_ship → shipped
  const shipOrder = (orderId) => {
    setOrders((prev) => prev.map((o) => (o.id === orderId
      ? { ...o, status: 'shipped', shippedAt: new Date().toISOString().slice(0, 10) }
      : o
    )));
    pushNotification(`${orderId} отгружен`, 'success');
  };

  // Закрыть автозаявку (поставлено → материал возвращается на max)
  const fulfillPurchaseRequest = (prId) => {
    setPurchaseRequests((prev) => prev.map((pr) => (pr.id === prId ? { ...pr, status: 'delivered', deliveredAt: new Date().toLocaleString('ru-RU').slice(0, 16) } : pr)));
    const pr = purchaseRequests.find((p) => p.id === prId);
    if (!pr) return;
    setSupermarkets((prev) => ({
      ...prev,
      raw: prev.raw.map((item) => (item.id === pr.materialId
        ? { ...item, current: Math.min(item.max, item.current + pr.qty) }
        : item
      )),
    }));
    const material = supermarkets.raw.find((r) => r.id === pr.materialId);
    pushNotification(`Поставка получена: ${material?.name}`, 'success');
  };

  return (
    <div style={{ minHeight: '100vh', background: C.bg, fontFamily: 'system-ui, -apple-system, sans-serif', color: C.text }}>
      {/* === ХЕДЕР === */}
      <header style={{ background: C.navy, color: '#fff', padding: '14px 24px', display: 'flex', alignItems: 'center', gap: 18, borderBottom: `3px solid ${C.accent}` }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
          <SonyaLogo height={48} />
          <div>
            <div style={{ fontWeight: 700, fontSize: 16, letterSpacing: 0.5 }}>SCM «Соня»</div>
            <div style={{ fontSize: 11, opacity: 0.75 }}>Управление цепочкой поставок</div>
          </div>
        </div>
        <div style={{ flex: 1 }} />
        <div style={{ fontSize: 13, opacity: 0.85 }}>Сегодня: 26 апреля 2026, 14:32</div>
        <div style={{ fontSize: 13, opacity: 0.85 }}>Производственный директор</div>
      </header>

      {/* === ВЕРХНЯЯ НАВИГАЦИЯ === */}
      <nav style={{ background: '#fff', borderBottom: `1px solid ${C.border}`, padding: '0 24px', display: 'flex', gap: 0 }}>
        {[
          { to: '/dashboard', label: 'Дашборд' },
          { to: '/orders', label: 'Заказы' },
          { to: '/kanban', label: 'Канбан-доска' },
          { to: '/supermarket', label: 'Супермаркеты' },
          { to: '/purchases', label: 'Закупки' },
          { to: '/analytics', label: 'Аналитика' },
        ].map((tab) => {
          // Бэйдж количества активных заявок на закупку
          const pendingPr = purchaseRequests.filter((pr) => pr.status === 'pending').length;
          const showBadge = tab.to === '/purchases' && pendingPr > 0;
          return (
            <NavLink
              key={tab.to}
              to={tab.to}
              style={({ isActive }) => ({
                padding: '14px 20px', background: 'none', border: 'none', cursor: 'pointer',
                fontSize: 14, fontWeight: isActive ? 600 : 500,
                color: isActive ? C.navy : C.textMuted,
                borderBottom: isActive ? `3px solid ${C.accent}` : '3px solid transparent',
                textDecoration: 'none',
                transition: 'all 0.15s', display: 'flex', alignItems: 'center', gap: 8,
              })}>
              {tab.label}
              {showBadge && (
                <span style={{ background: C.red, color: '#fff', borderRadius: 10, fontSize: 11, fontWeight: 700, padding: '1px 7px' }}>{pendingPr}</span>
              )}
            </NavLink>
          );
        })}
      </nav>

      {/* === КОНТЕНТ ЭКРАНА === */}
      <main style={{ padding: '24px', maxWidth: 1400, margin: '0 auto' }}>
        <Routes>
          <Route path="/" element={<Navigate to="/dashboard" replace />} />
          <Route path="/dashboard" element={<Dashboard orders={orders} supermarkets={supermarkets} purchaseRequests={purchaseRequests} />} />
          <Route path="/orders" element={<OrdersScreen orders={orders} onSelect={setSelectedOrder} onNewOrder={() => setIsNewOrderOpen(true)} onShip={shipOrder} />} />
          <Route path="/kanban" element={<KanbanBoard orders={orders} onMove={moveOrder} />} />
          <Route path="/supermarket" element={<SupermarketScreen supermarkets={supermarkets} purchaseRequests={purchaseRequests} />} />
          <Route path="/purchases" element={<PurchasesScreen purchaseRequests={purchaseRequests} supermarkets={supermarkets} onFulfill={fulfillPurchaseRequest} />} />
          <Route path="/analytics" element={<AnalyticsScreen orders={orders} shippedHistory={shippedHistory} />} />
          <Route path="*" element={<Navigate to="/dashboard" replace />} />
        </Routes>
      </main>

      {/* === МОДАЛКА ЗАКАЗА === */}
      {selectedOrder && <OrderModal order={selectedOrder} onClose={() => setSelectedOrder(null)} />}

      {/* === МОДАЛКА СОЗДАНИЯ ЗАКАЗА === */}
      {isNewOrderOpen && <NewOrderModal onClose={() => setIsNewOrderOpen(false)} onCreate={createOrder} />}

      {/* === ТОСТЫ === */}
      <div style={{ position: 'fixed', bottom: 20, right: 20, display: 'flex', flexDirection: 'column', gap: 10, zIndex: 200 }}>
        {notifications.map((n) => {
          const colors = {
            success: { bg: C.greenLight, border: C.green, text: '#3F6E1F' },
            warning: { bg: C.yellowLight, border: C.yellow, text: '#7A5A00' },
            info: { bg: C.ice, border: C.navy, text: C.navy },
          };
          const c = colors[n.type] || colors.info;
          return (
            <div key={n.id} style={{ background: c.bg, border: `1.5px solid ${c.border}`, color: c.text, padding: '10px 14px', borderRadius: 8, fontSize: 13, fontWeight: 500, boxShadow: '0 4px 12px rgba(0,0,0,0.08)', minWidth: 240 }}>
              {n.text}
            </div>
          );
        })}
      </div>

      {/* === ФУТЕР === */}
      <footer style={{ textAlign: 'center', padding: '20px 24px', color: C.textMuted, fontSize: 12, borderTop: `1px solid ${C.border}`, marginTop: 40, background: '#fff' }}>
        SCM «Соня» · MVP-прототип · ВКР Морозов А. А., гр. 22БИ-1, НИУ ВШЭ · 2026
      </footer>
    </div>
  );
}
